/* EXTRAÇÃO, TRANFORMAÇÃO, LOADING VIA SQL*/

-- CRIAÇÃO DATABASE PARA RECEBER TABELA DE DADOS
CREATE DATABASE LOCADORA_VEICULOS;

-- CONECTANDO A ESSA DATABASE
USE LOCADORA_VEICULOS;

/* 
A EXTRAÇÃO DOS DADOS POSSUI INCONVENIÊNCIAS DEVIDO À INSTALAÇÃO DO SQLSERVER
POIS QUANDO VAMOS IMPORTAR A PASTA EXCEL DA PROBLEMA POIS O SQLSERVER NÃO
CONSEGUE ENCONTRAR O ENGINE OLEDB.12 PARA IMPORTAÇÃO, ISSO É UM PROBLEMA
DA INSTALAÇÃO, POIS O SQL SERVER DEPENDE DE DRIVERS OLEDB PARA ABRIR ARQUIVOS 
EXCEL, E O DRIVER PADRÃO INSTALADO NÃO ENTENDE O FORMATO NOVO .XLSX.
COMO SOLUÇÃO RAPIDA, SALVAMOS O ARQUIVO EXCEL EM UMA VERSAO ANTIGA (Excel 97-2003 (.xls))
DESSA FORMA CONSEGUIMOS EXTRAIR OS DADOS SEM PROBLEMAS
*/

-- TRATANDO PLANILHA locacao_veiculos_copy.xls

-- RENOMEANDO TABELA "RASTREADOR$" -> Rastreador
EXEC sp_rename 'RASTREADOR', 'Rastreador';

-- EXPLORANDO OS DADOS
SELECT 
	* 
FROM 
	[LOCADORA_VEICULOS].[dbo].[Rastreador];

-- VALORES NULOS E COLUNAS DESNECESSÁRIAS ESTÃO POLUINDO OS DADOS
SELECT
	ID_CLIENTE,
	MARCA,
	PLACA,
	KILOMETRO_PERCORRIDO,
	ANO,
	[VALOR POR KM],
	[SITUAÇÃO CADASTRAL]
FROM
	[LOCADORA_VEICULOS].[dbo].[Rastreador]
WHERE
	ID_CLIENTE IS NOT NULL;

-- ANALISANDO TIPOS DAS COLUNAS
EXEC sp_help 'Rastreador';

-- ENRIQUECIMENTO DOS DADOS CRIANDO COLUNA PARA VALOR DA LOCAÇÃO (KM_PERCORRIDO * VALOR POR KM)
-- ALÉM DE FAZER O DE -> PARA DA SITUAÇÃO CADASTRAL, 1 É PAGO 0 É NÃO PAGO, DE ACORDO COM DOCUMENTAÇÃO

SELECT
	ID_CLIENTE,
	SUBSTRING(TRIM(MARCA), 1, CHARINDEX(' ', TRIM(MARCA)) - 1) AS MARCA,
	SUBSTRING(TRIM(MARCA), CHARINDEX(' ', TRIM(MARCA)) + 1, LEN(TRIM(MARCA))) AS MODELO,
	PLACA,
	KILOMETRO_PERCORRIDO,
	ANO,
	[VALOR POR KM],
	(KILOMETRO_PERCORRIDO * [VALOR POR KM]) AS VALOR_LOCAÇAO,
	(CASE
	WHEN [SITUAÇÃO CADASTRAL] = 1 THEN 'PAGO'
	ELSE 'NÃO PAGO' -- COMO DENTRO DO CONJUNTO SÓ EXISTEM ESSAS DUAS POSSIBILIDADES TRATAMOS COM ELSE
	END) AS SITUAÇAO_CADASTRAL
FROM
	[LOCADORA_VEICULOS].[dbo].[Rastreador]
WHERE
	ID_CLIENTE IS NOT NULL;

-- CRIANDO VIEW PARA TABELA TRATADA
CREATE VIEW VW_Rastreador AS
SELECT
	ID_CLIENTE,
	SUBSTRING(TRIM(MARCA), 1, CHARINDEX(' ', TRIM(MARCA)) - 1) AS MARCA,
	SUBSTRING(TRIM(MARCA), CHARINDEX(' ', TRIM(MARCA)) + 1, LEN(TRIM(MARCA))) AS MODELO,
	PLACA,
	KILOMETRO_PERCORRIDO,
	ANO,
	[VALOR POR KM],
	(KILOMETRO_PERCORRIDO * [VALOR POR KM]) AS VALOR_LOCAÇAO,
	(CASE
	WHEN [SITUAÇÃO CADASTRAL] = 1 THEN 'PAGO'
	ELSE 'NÃO PAGO' -- COMO DENTRO DO CONJUNTO SÓ EXISTEM ESSAS DUAS POSSIBILIDADES TRATAMOS COM ELSE
	END) AS SITUAÇAO_CADASTRAL
FROM
	[LOCADORA_VEICULOS].[dbo].[Rastreador]
WHERE
	ID_CLIENTE IS NOT NULL;

SELECT * FROM VW_Rastreador;

-- TRATANDO PLANILHA clientes_copy.xls


-- RENOMEANDO TABELA "Planilha1$" -> Clientes
EXEC sp_rename 'Planilha1$', 'Clientes';

-- EXPLORANDO OS DADOS
SELECT
	*
FROM
	[LOCADORA_VEICULOS].[dbo].[Clientes];

-- É UMA TABELA DIMENSÃO, LOGO NÃO PODE EXISTIR DUPLICIDADE NO CONJUNTO
-- ANALISANDO SE HÁ DUPLICIDADE NOS DADOS
SELECT
	ID,
	COUNT(ID) AS TOTAL_ID
FROM
	[LOCADORA_VEICULOS].[dbo].[Clientes]	
GROUP BY
	ID
HAVING
	COUNT(ID) > 1;
/* NAO HÁ DUPLICIDADE NOS DADOS*/

-- EXISTEM DADOS COM FORMATOS DIFERENTES, VAMOS PADRONIZAR OS DADOS
SELECT
	ID,
	UPPER(LEFT(NOME, 1)) + LOWER(SUBSTRING(NOME, 2, LEN(NOME))) AS NOME, -- TRATANDO COM UPPER
	LEFT(CARGO, 1) + LOWER(SUBSTRING(CARGO, 2, LEN(CARGO))) AS CARGO, -- TRATANDO SEM UPPER (AMBOS RETORNAM O MESMO RESULTADO)
	SALARIO,
	CIDADE
FROM 
	[LOCADORA_VEICULOS].[dbo].[Clientes];

-- CRIAÇÃO DA VIEW DA TABELA TRATADA
CREATE VIEW VW_Clients AS
SELECT
	ID,
	UPPER(LEFT(NOME, 1)) + LOWER(SUBSTRING(NOME, 2, LEN(NOME))) AS NOME,
	LEFT(CARGO, 1) + LOWER(SUBSTRING(CARGO, 2, LEN(CARGO))) AS CARGO,
	SALARIO,
	CIDADE
FROM
	[LOCADORA_VEICULOS].[dbo].[Clientes];

SELECT * FROM VW_Clients;
SELECT * FROM VW_Rastreador;




/* ANÁLISE DOS DADOS VIA SQL */

/* PERGUNTAS A SEREM RESPONDIDAS */

-- TOTAIS DE CLIENTES?
SELECT 
	COUNT(DISTINCT(ID)) AS CONT_CLIENTES_VW_Clients
FROM
	VW_Clients

SELECT 
	COUNT(DISTINCT(ID_CLIENTE)) AS CONT_CLIENTES_VW_Rastreador
FROM
	VW_Rastreador

/* EXISTEM CLIENTES QUE NÃO ESTÃO CADASTRADOSS! */

-- QUAIS CLIENTES NÃO ESTÃO CADASTRADOS?
SELECT
	ID_CLIENTE
FROM
	VW_Rastreador
WHERE
	ID_CLIENTE NOT IN
					(SELECT 
						C.ID
					FROM
						VW_Clients C
					JOIN VW_Rastreador R
					ON C.ID = R.ID_CLIENTE)
;

/*PARA TRATAR ESSE ERRO TEMOS QUE CADASTRAR OS VALORES DIRETAMENTE NA dbo.CLIENTES */

SELECT
	*
FROM
	[LOCADORA_VEICULOS].[dbo].[Clientes];

-- TRATANDO CLIENTES NAO CADASTRADOS
BEGIN TRAN
INSERT INTO [LOCADORA_VEICULOS].[dbo].[Clientes] (ID)
SELECT
	ID_CLIENTE
FROM
	VW_Rastreador
WHERE
	ID_CLIENTE NOT IN
					(SELECT 
						C.ID
					FROM
						VW_Clients C
					JOIN VW_Rastreador R
					ON C.ID = R.ID_CLIENTE)
;
COMMIT TRAN

/* 
	MESMO QUE A ÚNICA INFORMAÇÃO SEJAM OS ID's A TABELA DE REGISTRO DE CLIENTE FICA COMPLETA,
	SERIA NECESSÁRIO BUSCAR DE OUTRAS FORMAS, PARA PREENCHER CORRETAMENTE A TABELA DIMENSAO.
	NESSE CASO TEMOS PROBLEMAS DE LIMITAÇÃO DO CONJUNTO DE DADOS
*/
-- FATURAMENTO TOTAL?
SELECT
	FORMAT(SUM(R.VALOR_LOCAÇAO),'C','pt-Br') AS FATURAMENTO_TOTAL
FROM
	VW_Rastreador R; -- NOMEAMOS A VIEW PARA ENCONTRAR A COLUNA DE VALOR_LOCAÇAO MAIS FACILMENTE

/* FATURAMNETO_TOTAL = R$ 78.594,00*/

-- PERCENTUAL DE CLIENTES INADIMPLENTES?

-- Declarando variáveis
DECLARE @TOTAL_CLIENTES DECIMAL(5,1)
DECLARE @CLIENTES_NAOPAGO DECIMAL(5,1)
DECLARE @PERCENTUAL_INADIMPLENTES DECIMAL(5,2)

-- Atribuindo valores
SELECT 
	@CLIENTES_NAOPAGO = COUNT(ID_CLIENTE)
FROM 
	VW_Rastreador 
WHERE 
	SITUAÇAO_CADASTRAL = 'NÃO PAGO'

SELECT 
	@TOTAL_CLIENTES = COUNT(ID_CLIENTE)
FROM 
	VW_Rastreador

SET @PERCENTUAL_INADIMPLENTES = (@CLIENTES_NAOPAGO / @TOTAL_CLIENTES) * 100

-- Usando variáveis
SELECT CONVERT(NVARCHAR(10), @PERCENTUAL_INADIMPLENTES) + '%' AS PERCENTUAL_CLIENTES_INADIMPLENTES;

/* PERCENTUAL CLIENTES INADIMPLENTES = 23.33%*/

-- RECEBÍVEIS INADIMPLENTES?
SELECT
	FORMAT(SUM(R.VALOR_LOCAÇAO),'C','pt-Br') AS TOTAL_INADIMPLENTE
FROM
	VW_Rastreador R
WHERE 
	R.SITUAÇAO_CADASTRAL = 'NÃO PAGO';

/* RECEBÍVEIS INADIMPLENTES = R$ 18.860,00 */

-- FATURAMENTO AO LONGO DOS ANOS?
SELECT
	YEAR(R.ANO) AS ANO,
	FORMAT(SUM(R.VALOR_LOCAÇAO),'C','pt-Br') AS FATURAMENTO_TOTAL
FROM
	VW_Rastreador R
GROUP BY
	YEAR(R.ANO)
ORDER BY
	(SUM(R.VALOR_LOCAÇAO)) DESC;

/* FATURAMENTO AO LONGO DOS ANOS
	2015	R$ 34.872,00
	2019	R$ 20.016,00
	2016	R$ 16.538,00
	2014	R$ 3.874,00
	2017	R$ 3.294,00
*/

-- MARCAS MAIS LOCADAS?
SELECT
	R.MARCA,
	COUNT(R.ID_CLIENTE) AS QUANTIDADE
FROM
	VW_Rastreador R
GROUP BY
	R.MARCA
ORDER BY
	QUANTIDADE DESC;

/* MARCAS MAIS LOCADAS 
	MARCA	11
	TOYOTA	4
	VOLKSWAGEN	4
	RENAULT	2
	CHEVROLET	2
	FIAT	2
	FORD	2
	LAND_ROVER	2
	KIA	1
*/

/* 
	PROBBLEMA ! POIS A MARCA MAIS LOCADA É UMA MARCA QUE NAO FOI REGISTRADA,
	PERDEMOS INFORMAÇÃO RELEVANTE!!! MAIS UM CASO QUE ABRANGE O LIMITE DOS NOSSOS DADOS
*/

-- CIDADES MAIS LOCATÁRIAS?

SELECT
	C.CIDADE,
	COUNT(R.ID_CLIENTE) AS QUANTIDADE
FROM
	VW_Rastreador R
INNER JOIN VW_Clients C
ON R.ID_CLIENTE = C.ID
GROUP BY
	C.CIDADE
ORDER BY
	QUANTIDADE DESC;

/*	CIDADES MAIS LOCATÁRIAS
	OSASCO	11
	SÃO PAULO	9
	BARUERI	7
	NULL	3
*/

-- TOP 5 CLIENTES(CLIENTES COM MAIOR VALOR TOTAL DE LOCAÇÃO)?

SELECT TOP 5
	C.NOME,
	FORMAT(SUM(R.VALOR_LOCAÇAO),'C','pt-Br') AS TOTAL_GASTO
FROM
	VW_Rastreador R
INNER JOIN VW_Clients C
ON R.ID_CLIENTE = C.ID
GROUP BY
	C.NOME
ORDER BY
	SUM(R.VALOR_LOCAÇAO) DESC;

/* TOP 5 CLIENTES(CLIENTES COM MAIOR VALOR TOTAL DE LOCAÇÃO)
	Daniele	R$ 19.748,00
	Pietro	R$ 11.284,00
	Thomas	R$ 10.574,00
	Augusto	R$ 7.396,00
	Nathan	R$ 4.778,00
*/
	
-- TRAZER TABELA COM NOME, MARCA, MODELO, VALOR LOCAÇÃO E ANO

SELECT
	C.NOME,
	R.MARCA,
	R.MODELO,
	FORMAT(R.VALOR_LOCAÇAO,'C','pt-Br') AS VALOR_LOCACAO,
	YEAR(ANO) AS ANO
FROM
	VW_Rastreador R
INNER JOIN VW_Clients C
ON R.ID_CLIENTE = C.ID;

/*
NOME MARCA MODELO VALOR_LOCACAO ANO
Juliana silva	TOYOTA	HILUX	R$ 978,00	2015
Roberto gomes	TOYOTA	ETIOS	R$ 1.316,00	2015
Eduardo	VOLKSWAGEN	GOL	R$ 1.246,00	2015
André	TOYOTA	HILUX	R$ 370,00	2015
Antônio	RENAULT	LOGAN	R$ 2.500,00	2016
Augusto	VOLKSWAGEN	UP	R$ 7.396,00	2016
Breno	FIAT	SIENA	NULL	2017
Raissa	RENAULT	SANDERO	R$ 1.396,00	2017
Henrique	FORD	FOCUS	R$ 1.724,00	2017
Enrico	FORD	FIESTA	R$ 174,00	2017
Enzo	LAND_ROVER	EVOQUE	R$ 1.390,00	2016
Erick	FIAT	SIENA	R$ 1.770,00	2016
Felipe	CHEVROLET	CORSA	R$ 1.174,00	2014
Murilo	VOLKSWAGEN	GOL	R$ 1.392,00	2014
Henry	TOYOTA	HILUX	R$ 1.308,00	2014
Ian	LAND_ROVER	EVOQUE	R$ 1.962,00	2019
Isaac	VOLKSWAGEN	FUSCA	R$ 1.800,00	2019
João	MARCA	NÃO REGISTRADA	R$ 192,00	2019
Theo	MARCA	NÃO REGISTRADA	R$ 1.970,00	2016
Nathan	MARCA	NÃO REGISTRADA	R$ 4.778,00	2019
Otávio	MARCA	NÃO REGISTRADA	R$ 1.316,00	2016
Pietro	MARCA	NÃO REGISTRADA	R$ 11.284,00	2019
Thiago	MARCA	NÃO REGISTRADA	R$ 196,00	2016
Thomas	MARCA	NÃO REGISTRADA	R$ 10.574,00	2015
Vicente	MARCA	NÃO REGISTRADA	R$ 196,00	2015
Daniele	MARCA	NÃO REGISTRADA	R$ 19.748,00	2015
Vanessa	MARCA	NÃO REGISTRADA	R$ 444,00	2015
NULL	CHEVROLET	AGILE	NULL	2016
NULL	KIA	SOUL	NULL	2016
NULL	MARCA	NÃO REGISTRADA	NULL	2016
*/